version: '3'
services:
    app:
        container_name: classroom-app
        build:
            context: .
            dockerfile: docker/php-fpm/Dockerfile
        volumes:
            - .:/var/www/
        networks:
            - laravel-app
    nginx:
        image: nginx:alpine
        container_name: nginx-classroom
        ports:
            - "8123:80"
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./docker/nginx/logs:/var/log/nginx
        depends_on:
            - app
        networks:
            - laravel-app
    mysql:
        image: mysql:8.0
        container_name: classroom-db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel_app
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
        volumes:
            - ./docker/mysql:/var/lib/mysql
        ports:
            - 3310:3306
        networks:
            - laravel-app
    redis:
        image: redis:latest
        ports:
            - 6388:6379
        volumes:
            - ./docker/redis:/data
        networks:
            - laravel-app
networks:
    laravel-app:
